// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqaneqqwdsmlfsbhtixq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxYW5lcXF3ZHNtbGZzYmh0aXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTc0ODIsImV4cCI6MjA3MTc5MzQ4Mn0.lwZ-Z-OA1ZLf_gobrZkCYBriR-Ec5UUMRpT_cyux2jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});